### ISSUE TITLE
请问inference的时候对输入图像是怎么进行处理的啊

### ISSUE THREAD

**Issue by liu-zhenhua** [FeipengMa6/VLoRA#1]
RT，请问inference的时候图像信息是怎么输入到LLM里的呀，谢谢

**Comment by FeipengMa6** [comment]
The process involves the following steps:
1. Use the vision encoder to extract visual features of the input image.
2. Convert the visual features into perceptual weights (LoRA weights) using a perceptual weights generator.
3. Equip the LLM with the generated LoRA weights.
